version: "3"
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules           # anomious volume
    environment:
      - NODE_ENV=development"
    command: node index.js